---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by U.
--- DateTime: 2025/10/31 23:25
---
---比较之前存入redis的值是否和当前线程的值相同
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 相同则释放锁
    return redis.call('del', KEYS[1])
end
return 0